#spring:
#  ai:
#    mcp:
#      client:
#        enabled: true
#        name: my-mcp-client
#        version: 1.0.0
#        request-timeout: 30s
#        type: SYNC  # or ASYNC for reactive applications
#        tool-callback:
#          enabled: true
#        stdio:
#          # servers-configuration: classpath:mcp-servers.json
#          # 打包好的jar复制到指定位置
#          connections:
#            server1:
#              command: java
#              args:
#                - -jar
#                - D:/html/mcp-server-stdio-1.0.0-SNAPSHOT.jar
#                - --port=8080
#                - --mode=production